<script
    src='https://sleekflow.io/whatsapp-button.js'
    async
    onLoad="whatsappButton({
    buttonName:'Info XIA BOT',
    buttonIconSize: '22',
    brandImageUrl:'https://telegra.ph/file/f12faf59a412d274a76fa.png',
    buttonMargin:'true',
    brandName:'XB-ASISTENCIA',
    brandSubtitleText:'Por lo general, responde dentro de un día',
    buttonSize:'regular',
    buttonPosition:'left',
    callToAction:'Iniciar chat',
    phoneNumber:'59176181985',
    welcomeMessage:'Hola 👋',
    prefillMessage:'¡Hola, quiero saber más!',
    })"
    >
</script>